/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.CController;
import domain.Angazman;
import domain.Izvodjac;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class AngazmanKreirajDialog extends javax.swing.JDialog {

    private boolean uspeh = false;
    private Angazman angazman;

    /**
     * Creates new form AngazmanKreirajDialog
     */
    public AngazmanKreirajDialog(DogadjajKreirajDialog parent) {
        super(parent, true);
        initComponents();
        setTitle("Dodaj angažman");
        setLocationRelativeTo(parent);
        pripremiFormu();
    }

    public AngazmanKreirajDialog(DogadjajKreirajDialog parent, Angazman angazmanZaIzmenu) {
        super(parent, true);
        initComponents();
        this.angazman = angazmanZaIzmenu;
        setTitle("Izmeni angažman");
        setLocationRelativeTo(parent);
        pripremiFormu();
        popuniPolja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxIzvodjac = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTrajanje = new javax.swing.JTextField();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxIzvodjac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Izvodjac:");

        jLabel2.setText("Trajanje");

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jButtonOtkazi.setText("Otkazi");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxIzvodjac, 0, 125, Short.MAX_VALUE)
                    .addComponent(jTextFieldTrajanje))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButtonOtkazi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(jButtonSacuvaj)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxIzvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSacuvaj)
                    .addComponent(jButtonOtkazi))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        try {
            Izvodjac izvodjac = (Izvodjac) jComboBoxIzvodjac.getSelectedItem();
            if (izvodjac == null) {
                throw new Exception("Morate izabrati izvođača!");
            }
            int trajanje = Integer.parseInt(jTextFieldTrajanje.getText().trim());
            if (trajanje <= 0) {
                throw new Exception("Trajanje nastupa mora biti pozitivan broj!");
            }
            
            if (this.angazman == null) { // Ako je dodavanje
                this.angazman = new Angazman(null, izvodjac, trajanje);
            } else { // Ako je izmena
                this.angazman.setIzvodjac(izvodjac);
                this.angazman.setTrajanjeNastupa(trajanje);
            }
            
            this.uspeh = true;
            this.dispose();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Trajanje mora biti broj!", "Greška", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOtkazi;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JComboBox jComboBoxIzvodjac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldTrajanje;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        try {
            jComboBoxIzvodjac.removeAllItems();
            ArrayList<Izvodjac> izvodjaci = CController.getInstance().vratiSveIzvodjace();
            for (Izvodjac i : izvodjaci) {
                jComboBoxIzvodjac.addItem(i);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju izvođača!", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void popuniPolja() {
        jComboBoxIzvodjac.setSelectedItem(angazman.getIzvodjac());
        jTextFieldTrajanje.setText(String.valueOf(angazman.getTrajanjeNastupa()));
    }
public boolean isUspeh() {
        return uspeh;
    }

    public Angazman getNoviAngazman() {
        return this.angazman;
    }

    
}
