/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.CController;
import domain.Angazman;
import domain.Dogadjaj;
import domain.Lokacija;
import domain.Potvrda;
import enums.VrstaDogadjaja;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import session.Session;
import tableModels.TableModelAngazman;
import tableModels.TableModelPotvrda;

/**
 *
 * @author user
 */
public class DogadjajKreirajDialog extends javax.swing.JDialog {
    
private final JFrame parentForm;
    private Dogadjaj dogadjaj;
    // Format datuma koji ,mora da buyde
    private final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm");
    /**
     * Creates new form DogadjajKreirajDialog
     */
    public DogadjajKreirajDialog(DogadjajimaUpravljajForm parent) {
        super(parent, true);
        initComponents();
        this.parentForm = parent;
        this.dogadjaj = new Dogadjaj(); //  prazan objekat
        this.dogadjaj.setAngazmani(new ArrayList<>()); 
        this.dogadjaj.setPotvrde(new ArrayList<>());
        
        setTitle("Kreiraj novi događaj");
        setLocationRelativeTo(parent);
        
        pripremiFormu();
       
    }
    public DogadjajKreirajDialog(JFrame parent) {
        super(parent, true);
        initComponents();
        this.parentForm = parent;
        this.dogadjaj = new Dogadjaj();
        this.dogadjaj.setAngazmani(new ArrayList<>()); 
        this.dogadjaj.setPotvrde(new ArrayList<>());
        
        setTitle("Kreiraj novi događaj");
        setLocationRelativeTo(parent);
        JOptionPane.showMessageDialog(this, "Sistem je kreirao dogadjaj!", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
        pripremiFormu();
    }
    public DogadjajKreirajDialog(DogadjajimaUpravljajForm parent, Dogadjaj dogadjajZaIzmenu) {
        super(parent, true);
        initComponents();
        this.parentForm = parent;
        this.dogadjaj = dogadjajZaIzmenu;
        
        setTitle("Detalji / Izmena događaja");
        setLocationRelativeTo(parent);
        
        pripremiFormu();
        popuniFormu();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNazivDogadjaja = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxLokacija = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDatumVreme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxVrstaDogadjaja = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAngazmani = new javax.swing.JTable();
        jButtonDodajAng = new javax.swing.JButton();
        jButtonIzmeniAng = new javax.swing.JButton();
        jButtonObrisiAng = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePotvrde = new javax.swing.JTable();
        jButtonDodajGosta = new javax.swing.JButton();
        jButtonObrisiGosta = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv Dogadjaja:");

        jLabel2.setText("Lokacija:");

        jComboBoxLokacija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Datum i vreme:");

        jTextFieldDatumVreme.setText("09.11.2025 20:22");

        jLabel4.setText("Vrsta dogadjaja:");

        jComboBoxVrstaDogadjaja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Angazovani Izvodjaci:");

        jTableAngazmani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAngazmani);

        jButtonDodajAng.setText("Dodaj");
        jButtonDodajAng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajAngActionPerformed(evt);
            }
        });

        jButtonIzmeniAng.setText("Izmeni");
        jButtonIzmeniAng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniAngActionPerformed(evt);
            }
        });

        jButtonObrisiAng.setText("Obrisi");
        jButtonObrisiAng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiAngActionPerformed(evt);
            }
        });

        jLabel6.setText("Pozvani Gosti:");

        jTablePotvrde.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablePotvrde);

        jButtonDodajGosta.setText("Dodaj");
        jButtonDodajGosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajGostaActionPerformed(evt);
            }
        });

        jButtonObrisiGosta.setText("Obrisi");
        jButtonObrisiGosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiGostaActionPerformed(evt);
            }
        });

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jButtonOtkazi.setText("Otkazi");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNazivDogadjaja, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxLokacija, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDatumVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxVrstaDogadjaja, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDodajAng)
                            .addComponent(jButtonObrisiAng)
                            .addComponent(jButtonIzmeniAng)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDodajGosta)
                            .addComponent(jButtonObrisiGosta)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel6)))
                .addGap(126, 126, 126))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177)
                .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButtonDodajGosta)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonObrisiGosta))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNazivDogadjaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxLokacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDatumVreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxVrstaDogadjaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDodajAng)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonIzmeniAng)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonObrisiAng)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIzmeniAngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniAngActionPerformed
        int red = jTableAngazmani.getSelectedRow();
    if (red == -1) {
        JOptionPane.showMessageDialog(this, "Morate izabrati angažman za izmenu!", "Greška", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    TableModelAngazman model = (TableModelAngazman) jTableAngazmani.getModel();
    Angazman angazmanZaIzmenu = model.getAngazman(red); 
    
    AngazmanKreirajDialog editDialog = new AngazmanKreirajDialog(this, angazmanZaIzmenu);
    editDialog.setVisible(true);
    
    if (editDialog.isUspeh()) {
        model.fireTableDataChanged();
    }
    }//GEN-LAST:event_jButtonIzmeniAngActionPerformed

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    private void jButtonDodajAngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajAngActionPerformed

        AngazmanKreirajDialog addAngazmanDialog = new AngazmanKreirajDialog(this);
        addAngazmanDialog.setVisible(true); 
        
        if (addAngazmanDialog.isUspeh()) {
            Angazman noviAngazman = addAngazmanDialog.getNoviAngazman();
            TableModelAngazman model = (TableModelAngazman) jTableAngazmani.getModel();
            model.dodajAngazman(noviAngazman);
        }
    }//GEN-LAST:event_jButtonDodajAngActionPerformed

    private void jButtonObrisiAngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiAngActionPerformed
        int selektovanRed = jTableAngazmani.getSelectedRow();
        if (selektovanRed == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati angažman za brisanje.", "Greška", JOptionPane.WARNING_MESSAGE);
            return;
        }
        TableModelAngazman model = (TableModelAngazman) jTableAngazmani.getModel();
        model.obrisiAngazman(selektovanRed);
        JOptionPane.showMessageDialog(this, "Angažman je uklonjen iz liste.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonObrisiAngActionPerformed

    private void jButtonDodajGostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajGostaActionPerformed
         System.out.println("--- AKCIJA: Dugme 'Dodaj Gosta' kliknuto ---");
        PotvrdaGostaKreirajDialog addGostDialog = new PotvrdaGostaKreirajDialog(this);
    addGostDialog.setVisible(true);

    if (addGostDialog.isUspeh()) {
        System.out.println("GostDodajNaDogadjajDialog je vratio 'uspeh'.");
        TableModelPotvrda model = (TableModelPotvrda) jTablePotvrde.getModel();
        ArrayList<Potvrda> postojecePotvrde = model.getListaPotvrda(); 
        System.out.println("Broj gostiju koji VEĆ POSTOJE u tabeli: " + postojecePotvrde.size());
        ArrayList<Potvrda> novePotvrde = addGostDialog.getDodatePotvrde();
        System.out.println("Broj gostiju IZABRANIH u dijalogu: " + novePotvrde.size());
        int brojDodatih = 0;
        for(Potvrda p : novePotvrde) {
            System.out.println("   - Izabran gost: ID=" + p.getGost().getGostId() + ", Ime=" + p.getGost().getIme());
        }
        for (Potvrda novaPotvrda : novePotvrde) {
            
            boolean vecPostoji = false;
            for (Potvrda postojeca : postojecePotvrde) {
                if (postojeca.getGost().getGostId() == novaPotvrda.getGost().getGostId()) {
                    System.out.println("DUPLIKAT PRONAĐEN: Gost sa ID " + novaPotvrda.getGost().getGostId() + " već postoji na listi. PRESKAČEM.");
                    vecPostoji = true;
                    break; 
                }
            }
           
            if (!vecPostoji) {
                System.out.println("DODAJEM GOSTA: Gost sa ID " + novaPotvrda.getGost().getGostId() + " se dodaje u tabelu.");
                novaPotvrda.setDatumVreme(LocalDateTime.now()); 
                model.dodajPotvrdu(novaPotvrda);
                brojDodatih++;
            }
        }
         System.out.println("Ukupno novih gostiju dodato u tabelu: " + brojDodatih);
        System.out.println("-------------------------------------------------");
        if (brojDodatih > 0) {
            JOptionPane.showMessageDialog(this, "Uspešno dodato " + brojDodatih + " novih gostiju.", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Nijedan novi gost nije dodat (izabrani već postoje na listi).", "Info", JOptionPane.WARNING_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButtonDodajGostaActionPerformed

    private void jButtonObrisiGostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiGostaActionPerformed
        int[] selektovaniRedovi = jTablePotvrde.getSelectedRows();
        if (selektovaniRedovi.length == 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati gosta za uklanjanje.", "Greška", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Arrays.sort(selektovaniRedovi);
        TableModelPotvrda model = (TableModelPotvrda) jTablePotvrde.getModel();
        // mora od pozadi da se brise
        for (int i = selektovaniRedovi.length-1; i >=0 ; i--) {
            int redZaBrisanje = selektovaniRedovi[i];
        model.obrisiPotvrdu(redZaBrisanje);
        }
        JOptionPane.showMessageDialog(this, "Gost je uklonjen sa liste.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonObrisiGostaActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        try {
    
            if (jTextFieldNazivDogadjaja.getText().trim().isEmpty()) {
                throw new Exception("Naziv događaja je obavezan!");
            }
            dogadjaj.setNaziv(jTextFieldNazivDogadjaja.getText().trim());
                
            try {
                dogadjaj.setDatumVreme(LocalDateTime.parse(jTextFieldDatumVreme.getText().trim(), dtf));
            } catch (Exception e) {
                throw new Exception("Datum i vreme nisu u ispravnom formatu (dd.MM.yyyy HH:mm)!");
            }
            
            dogadjaj.setLokacija((Lokacija) jComboBoxLokacija.getSelectedItem());
            dogadjaj.setVrstaDogadjaja((VrstaDogadjaja) jComboBoxVrstaDogadjaja.getSelectedItem());
            dogadjaj.setKorisnik(Session.getInstance().getUlogovaniKorisnik());
            
            TableModelAngazman modelAngazman = (TableModelAngazman) jTableAngazmani.getModel();
            dogadjaj.setAngazmani(modelAngazman.getListaAngazmana());
            
            TableModelPotvrda modelPotvrda = (TableModelPotvrda) jTablePotvrde.getModel();
            dogadjaj.setPotvrde(modelPotvrda.getListaPotvrda());

            if (dogadjaj.getDogadjajId() == 0 || dogadjaj.getDogadjajId() == -1) { //
                CController.getInstance().kreirajDogadjaj(dogadjaj);
                JOptionPane.showMessageDialog(this, "Sistem je uspešno kreirao događaj.", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            } else {
                CController.getInstance().izmeniDogadjaj(dogadjaj);
                JOptionPane.showMessageDialog(this, "Sistem je uspešno sačuvao izmene.", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            }
            

            if (parentForm instanceof DogadjajimaUpravljajForm) {
                DogadjajimaUpravljajForm formaZaUpravljanje = (DogadjajimaUpravljajForm) parentForm;
                formaZaUpravljanje.osveziPrikaz();
            }
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška pri čuvanju", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajAng;
    private javax.swing.JButton jButtonDodajGosta;
    private javax.swing.JButton jButtonIzmeniAng;
    private javax.swing.JButton jButtonObrisiAng;
    private javax.swing.JButton jButtonObrisiGosta;
    private javax.swing.JButton jButtonOtkazi;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JComboBox jComboBoxLokacija;
    private javax.swing.JComboBox jComboBoxVrstaDogadjaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAngazmani;
    private javax.swing.JTable jTablePotvrde;
    private javax.swing.JTextField jTextFieldDatumVreme;
    private javax.swing.JTextField jTextFieldNazivDogadjaja;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        // Popuni ComboBox za lokacije
        try {
            jComboBoxLokacija.removeAllItems();
            ArrayList<Lokacija> lokacije = CController.getInstance().vratiSveLokacije();
            for (Lokacija l : lokacije) {
                jComboBoxLokacija.addItem(l);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju lokacija!", "Greška", JOptionPane.ERROR_MESSAGE);
        }
        
        jComboBoxVrstaDogadjaja.removeAllItems();
        for (VrstaDogadjaja vrsta : VrstaDogadjaja.values()) {
            jComboBoxVrstaDogadjaja.addItem(vrsta);
        }
  
        jTableAngazmani.setModel(new TableModelAngazman(dogadjaj.getAngazmani()));
        jTablePotvrde.setModel(new TableModelPotvrda(dogadjaj.getPotvrde()));
    }
    
    private void popuniFormu() {
        jTextFieldNazivDogadjaja.setText(dogadjaj.getNaziv());
        jTextFieldDatumVreme.setText(dtf.format(dogadjaj.getDatumVreme()));
        jComboBoxLokacija.setSelectedItem(dogadjaj.getLokacija());
        jComboBoxVrstaDogadjaja.setSelectedItem(dogadjaj.getVrstaDogadjaja());
    }

}
