/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import tableModels.TableModelDogadjaj;
import domain.Dogadjaj;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import controller.CController;
import domain.Angazman;
import domain.Potvrda;
import java.util.ArrayList;

/**
 *
 * @author user
 */
public class DogadjajimaUpravljajForm extends javax.swing.JFrame {

    /**
     * Creates new form DogadjajimaUpravljajForm
     */
    public DogadjajimaUpravljajForm() {
        initComponents();
        setTitle("Upravljanje događajima");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);


        TableModelDogadjaj model = new TableModelDogadjaj();
        jTableDogadjaji.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDogadjaji = new javax.swing.JTable();
        jButtonKreiraj = new javax.swing.JButton();
        jButtonDetalji = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jButtonZatvori = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableDogadjaji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDogadjaji);

        jButtonKreiraj.setText("Dodaj");
        jButtonKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajActionPerformed(evt);
            }
        });

        jButtonDetalji.setText("Izmeni");
        jButtonDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonZatvori.setText("Otkazi");
        jButtonZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZatvoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonKreiraj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButtonObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiActionPerformed
        int selektovanRed = jTableDogadjaji.getSelectedRow();
        if (selektovanRed == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati događaj za prikaz detalja!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            TableModelDogadjaj model = (TableModelDogadjaj) jTableDogadjaji.getModel();
            Dogadjaj dogadjajZaPrikaz = model.getDogadjaj(selektovanRed);

            ArrayList<Angazman> angazmani = CController.getInstance().vratiAngazmaneZaDogadjaj(dogadjajZaPrikaz);
            for (Angazman a : angazmani) {
                a.setDogadjaj(dogadjajZaPrikaz);
            }
            dogadjajZaPrikaz.setAngazmani(angazmani);

            ArrayList<Potvrda> potvrde = CController.getInstance().vratiPotvrdeZaDogadjaj(dogadjajZaPrikaz);
            for (Potvrda p : potvrde) {
                p.setDogadjaj(dogadjajZaPrikaz);
            }
            dogadjajZaPrikaz.setPotvrde(potvrde);

            new DogadjajKreirajDialog(this, dogadjajZaPrikaz).setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju detalja o događaju: " + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonDetaljiActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        int selektovanRed = jTableDogadjaji.getSelectedRow();
        if (selektovanRed == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati događaj za brisanje!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni? Brisanje događaja će obrisati i sve povezane angažmane i potvrde.", "Potvrda brisanja", JOptionPane.YES_NO_OPTION);
        if (odgovor == JOptionPane.YES_OPTION) {
            try {
                TableModelDogadjaj model = (TableModelDogadjaj) jTableDogadjaji.getModel();
                Dogadjaj dogadjajZaBrisanje = model.getDogadjaj(selektovanRed);

                CController.getInstance().obrisiDogadjaj(dogadjajZaBrisanje);
                JOptionPane.showMessageDialog(this, "Događaj je uspešno obrisan.", "Uspeh", JOptionPane.INFORMATION_MESSAGE);

                osveziPrikaz();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Došlo je do greške pri brisanju: " + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZatvoriActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonZatvoriActionPerformed

    private void jButtonKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajActionPerformed
        new DogadjajKreirajDialog(this).setVisible(true);
    }//GEN-LAST:event_jButtonKreirajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalji;
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonZatvori;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDogadjaji;
    // End of variables declaration//GEN-END:variables
 void osveziPrikaz() {
        TableModelDogadjaj model = (TableModelDogadjaj) jTableDogadjaji.getModel();
        model.osveziTabelu();
    }

}
