/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.CController;
import domain.Izvodjac;
import enums.Zanr;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class IzvodjacaKreirajDialog extends javax.swing.JDialog {
private JFrame parentForm;
    private Izvodjac izvodjac;
    /**
     * Creates new form KreirajIzvodjacaDialog
     */
    public IzvodjacaKreirajDialog(IzvodjacimaUpravljajForm parent) {
        super(parent, true);
        initComponents();
        this.parentForm = parent;
        this.izvodjac = null;
        setTitle("Kreiraj novog izvodjaca");
        setLocationRelativeTo(parent);
        popuniZanrove();
    }
    public IzvodjacaKreirajDialog(JFrame parent) {
        super(parent, true);
        initComponents();
        this.parentForm = parent;
        this.izvodjac = null;
        setTitle("Kreiraj novog izvodjaca");
        setLocationRelativeTo(parent);
        popuniZanrove();
        JOptionPane.showMessageDialog(this, "Sistem je kreirao izvodjaca!", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
        
    }
    public IzvodjacaKreirajDialog ( IzvodjacimaUpravljajForm parent, Izvodjac izvodjacZaIzmenu) {
        super(parent, true);
        initComponents();
        this.parentForm = parent;
        this.izvodjac = izvodjacZaIzmenu;
        setTitle("Izmeni izvodjaca");
        setLocationRelativeTo(parent);
        popuniZanrove();
        popuniPolja();
    }

    private void popuniZanrove() {
        jComboBoxZanr.removeAllItems();
        for (Zanr z : Zanr.values()) {
            jComboBoxZanr.addItem(z);
        }
    }
    
    private void popuniPolja() {
        jTextFieldIme.setText(izvodjac.getIme());
        jComboBoxZanr.setSelectedItem(izvodjac.getZanr());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jButtonOdustani = new javax.swing.JButton();
        jComboBoxZanr = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonSave.setText("SAVE");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabel2.setText("Ime:");

        jLabel3.setText("Zanr:");

        jButtonOdustani.setText("ODUSTANI");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jComboBoxZanr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIme, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(jComboBoxZanr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButtonOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxZanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try {
            String ime = jTextFieldIme.getText().trim();
            if (ime.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ime izvođača je obavezno!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Zanr zanr = (Zanr) jComboBoxZanr.getSelectedItem();
            
            if (this.izvodjac == null) {
                Izvodjac noviIzvodjac = new Izvodjac(-1, ime, zanr);
                CController.getInstance().kreirajIzvodjaca(noviIzvodjac);
                JOptionPane.showMessageDialog(this, "Izvođač je uspešno sačuvan!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            } else {
                this.izvodjac.setIme(ime);
                this.izvodjac.setZanr(zanr);
                CController.getInstance().izmeniIzvodjaca(this.izvodjac);
                JOptionPane.showMessageDialog(this, "Izvođač je uspešno izmenjen!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            }
            
            if (parentForm instanceof IzvodjacimaUpravljajForm) {
                IzvodjacimaUpravljajForm formaZaUpravljanje = (IzvodjacimaUpravljajForm) parentForm;
                formaZaUpravljanje.osveziPrikaz();
            }
            this.dispose();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Došlo je do greške: " + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboBoxZanr;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldIme;
    // End of variables declaration//GEN-END:variables
}
