/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.CController;
import domain.Korisnik;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class KorisnikaKreirajDialog extends javax.swing.JDialog {

    /**
     * Creates new form KorisnikaKreirajDialog
     */
    private final JFrame parentFrame;
    private Korisnik korisnik;

    // Konstruktor za DODAVANJE
    public KorisnikaKreirajDialog(JFrame parent) {
        super(parent, true);
        initComponents();
        this.parentFrame = parent;
        this.korisnik = null;
        setTitle("Kreiraj novog korisnika");
        setLocationRelativeTo(parent);
        JOptionPane.showMessageDialog(this, "Sistem je kreirao korisnika!", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
    }
    
    // Konstruktor za IZMENU
    public KorisnikaKreirajDialog(JFrame parent, Korisnik korisnikZaIzmenu) {
        super(parent, true);
        initComponents();
        this.parentFrame = parent;
        this.korisnik = korisnikZaIzmenu;
        setTitle("Izmeni korisnika");
        setLocationRelativeTo(parent);
        popuniPolja();
        
        // Pri izmeni, lozinka se ne prikazuje i nije obavezna za promenu
        jPasswordFieldLozinka.setEnabled(false);
        // Možeš dodati i labelu koja kaže "Ostavite prazno ako ne želite promenu"
    }

    private void popuniPolja() {
        jTextFieldIme.setText(korisnik.getIme());
        jTextFieldPrezime.setText(korisnik.getPrezime());
        jTextFieldEmail.setText(korisnik.getEmail());
        jTextFieldEmail.setEnabled(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonSacuvaj2 = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldIme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldLozinka = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel3.setText("Email:");

        jButtonSacuvaj2.setText("Sacuvaj");
        jButtonSacuvaj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvaj2ActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jLabel4.setText("Lozinka:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67)
                        .addComponent(jTextFieldIme))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jButtonSacuvaj2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldLozinka)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordFieldLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSacuvaj2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvaj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvaj2ActionPerformed
        try {
            String ime = jTextFieldIme.getText().trim();
            String prezime = jTextFieldPrezime.getText().trim();
            String email = jTextFieldEmail.getText().trim();
            String lozinka = String.valueOf(jPasswordFieldLozinka.getPassword());
            
            if (ime.isEmpty() || prezime.isEmpty() || email.isEmpty()) {
                throw new Exception("Ime, prezime i email su obavezna polja!");
            }
            
            if (this.korisnik == null) { // --- DODAVANJE ---
                if (lozinka.isEmpty()) {
                    throw new Exception("Lozinka je obavezna pri kreiranju korisnika!");
                }
                Korisnik novi = new Korisnik(-1, ime, prezime, email, lozinka);
                CController.getInstance().kreirajKorisnika(novi);
                JOptionPane.showMessageDialog(this, "Korisnik je uspešno kreiran!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            } else { // --- IZMENA ---
                this.korisnik.setIme(ime);
                this.korisnik.setPrezime(prezime);
                // Ako je korisnik uneo novu lozinku, postavi je. Ako nije, ne diraj staru.
                // Na serveru će biti potrebna posebna logika za ovo.
                if (!lozinka.isEmpty()) {
                    this.korisnik.setLozinka(lozinka);
                }
                CController.getInstance().promeniKorisnika(this.korisnik);
                JOptionPane.showMessageDialog(this, "Podaci su uspešno izmenjeni!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            }
            if (parentFrame instanceof KorisnicimaUpravljajForm) {
                ((KorisnicimaUpravljajForm) parentFrame).osveziPrikaz();
            }
            
            this.dispose();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSacuvaj2ActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JButton jButtonSacuvaj1;
    private javax.swing.JButton jButtonSacuvaj2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordFieldLozinka;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables
}
