/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CController;
import domain.Korisnik;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tableModels.TableModelKorisnik;

/**
 *
 * @author user
 */
public class KorisnicimaUpravljajForm extends javax.swing.JFrame {

    /**
     * Creates new form KorisnicimaUpravljajForm
     */
    public KorisnicimaUpravljajForm() {
        initComponents();
        setTitle("Upravljanje korisnicima (organizatorima)");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        jTableKorisnici.setModel(new TableModelKorisnik());
        
        // Onemogući dugmiće na početku
        jButtonIzmeni.setEnabled(false);
        jButtonObrisi.setEnabled(false);
        
        // Dodaj listener na tabelu
        jTableKorisnici.getSelectionModel().addListSelectionListener(e -> {
            boolean isRowSelected = jTableKorisnici.getSelectedRow() != -1;
            jButtonIzmeni.setEnabled(isRowSelected);
            jButtonObrisi.setEnabled(isRowSelected);
        });
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKorisnici = new javax.swing.JTable();
        jButtonIzmeni = new javax.swing.JButton();
        jButtonDodaj = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jButtonZatvori = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableKorisnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableKorisnici);

        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jButtonDodaj.setText("Dodaj");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonZatvori.setText("Otkazi");
        jButtonZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZatvoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonZatvori)
                    .addComponent(jButtonIzmeni)
                    .addComponent(jButtonDodaj)
                    .addComponent(jButtonObrisi))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButtonDodaj)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonIzmeni)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonObrisi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButtonZatvori)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        new KorisnikaKreirajDialog(this).setVisible(true);
    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
       int red = jTableKorisnici.getSelectedRow();
        if (red == -1) return; // Listener ovo već sprečava, ali za svaki slučaj
        
        Korisnik k = ((TableModelKorisnik) jTableKorisnici.getModel()).getKorisnik(red);
        new KorisnikaKreirajDialog(this, k).setVisible(true);
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        int red = jTableKorisnici.getSelectedRow();
        if (red == -1) return;
        
        int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni?", "Potvrda brisanja", JOptionPane.YES_NO_OPTION);
        if (odgovor == JOptionPane.YES_OPTION) {
            try {
                Korisnik k = ((TableModelKorisnik) jTableKorisnici.getModel()).getKorisnik(red);
                CController.getInstance().obrisiKorisnika(k);
                JOptionPane.showMessageDialog(this, "Korisnik je obrisan.", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
                osveziPrikaz();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Greška pri brisanju: " + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZatvoriActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonZatvoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KorisnicimaUpravljajForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KorisnicimaUpravljajForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KorisnicimaUpravljajForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KorisnicimaUpravljajForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KorisnicimaUpravljajForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonZatvori;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKorisnici;
    // End of variables declaration//GEN-END:variables
   
     void osveziPrikaz() {
        jTableKorisnici.setModel(new TableModelKorisnik());
        TableModelKorisnik model = (TableModelKorisnik) jTableKorisnici.getModel();
        jButtonIzmeni.setEnabled(false);
        jButtonObrisi.setEnabled(false);
        model.osveziTabelu();
    }
}
