/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.CController;
import domain.Lokacija;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class LokacijuKreirajDialog extends javax.swing.JDialog {
private JFrame parentForm;
    private Lokacija lokacija;
    /**
     * Creates new form KreirajLokacijuDialog
     */
    public LokacijuKreirajDialog(LokacijomUpravljajForm parent) {
        super(parent, true); // true = modalni dijalog
        initComponents();
        this.parentForm = parent;
        this.lokacija = null;
        setTitle("Kreiraj novu lokaciju");
        setLocationRelativeTo(parent);
    }
    public LokacijuKreirajDialog(JFrame parent) {
        super(parent, true);
        initComponents();
        this.parentForm = parent;
        this.lokacija = null;
        setTitle("Kreiraj novu lokaciju");
        setLocationRelativeTo(parent);
        JOptionPane.showMessageDialog(this, "Sistem je kreirao lokaciju!", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
    }
    public LokacijuKreirajDialog(LokacijomUpravljajForm parent, Lokacija lokacijaZaIzmenu) {
        super(parent, true);
        initComponents();
        this.parentForm = parent;
        this.lokacija = lokacijaZaIzmenu;
        setTitle("Izmeni lokaciju");
        setLocationRelativeTo(parent);
        popuniPolja(); 
    }

    private void popuniPolja() {
        jTextFieldNaziv.setText(lokacija.getNaziv());
        jTextFieldAdresa.setText(lokacija.getAdresa());
        jTextFieldKapacitet.setText(String.valueOf(lokacija.getKapacitet()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jTextFieldAdresa = new javax.swing.JTextField();
        jTextFieldKapacitet = new javax.swing.JTextField();
        jButtonOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonSave.setText("SAVE");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabel2.setText("Naziv:");

        jLabel3.setText("Adresa:");

        jLabel4.setText("Kapacitet:");

        jButtonOdustani.setText("ODUSTANI");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(jTextFieldAdresa)
                            .addComponent(jTextFieldKapacitet))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButtonOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldKapacitet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try {
            // Validacija
            String naziv = jTextFieldNaziv.getText().trim();
            String adresa = jTextFieldAdresa.getText().trim();
            if (naziv.isEmpty() || adresa.isEmpty() || jTextFieldKapacitet.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sva polja su obavezna!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int kapacitet = Integer.parseInt(jTextFieldKapacitet.getText().trim());
            if (kapacitet <= 0) {
                 JOptionPane.showMessageDialog(this, "Kapacitet mora biti pozitivan broj!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (this.lokacija == null) {
                // --- DODAVANJE ---
                Lokacija novaLokacija = new Lokacija(-1, naziv, adresa, kapacitet);
                CController.getInstance().kreirajLokaciju(novaLokacija);
                JOptionPane.showMessageDialog(this, "Lokacija je uspešno sačuvana!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // --- IZMENA ---
                this.lokacija.setNaziv(naziv);
                this.lokacija.setAdresa(adresa);
                this.lokacija.setKapacitet(kapacitet);
                CController.getInstance().izmeniLokaciju(this.lokacija);
                JOptionPane.showMessageDialog(this, "Lokacija je uspešno izmenjena!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            }
            
            if (parentForm instanceof LokacijomUpravljajForm) {
                LokacijomUpravljajForm formaZaUpravljanje = (LokacijomUpravljajForm) parentForm;
                formaZaUpravljanje.osveziPrikaz();
            }
            this.dispose(); 
            
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Kapacitet mora biti broj!", "Greška", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Došlo je do greške: " + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldAdresa;
    private javax.swing.JTextField jTextFieldKapacitet;
    private javax.swing.JTextField jTextFieldNaziv;
    // End of variables declaration//GEN-END:variables
}
