/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CController;
import domain.Korisnik;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import session.Session;

/**
 *
 * @author user
 */
public class MainForm extends javax.swing.JFrame {

    Korisnik korisnik;

    /**
     * Creates new form MainForm
     */
    public MainForm(Korisnik ulogovaniKorisnik) {
        initComponents();
        korisnik = ulogovaniKorisnik;
        setTitle("Main Form");
        jLabel1.setText("Dobrodosli, " + korisnik.getIme() + "!");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemKG = new javax.swing.JMenuItem();
        jMenuItemUG = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemKL = new javax.swing.JMenuItem();
        jMenuItemUL = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemKI = new javax.swing.JMenuItem();
        jMenuItemUI = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Izloguj se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu.setText("Dogadjaji");

        jMenuItem1.setText("Kreiraj");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem1);

        jMenuItem2.setText("Upravljaj");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem2);

        jMenuBar1.add(jMenu);

        jMenu2.setText("Gosti");

        jMenuItemKG.setText("Kreiraj");
        jMenuItemKG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKGActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemKG);

        jMenuItemUG.setText("Upravljaj");
        jMenuItemUG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUGActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemUG);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Lokacije");

        jMenuItemKL.setText("Kreiraj");
        jMenuItemKL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKLActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemKL);

        jMenuItemUL.setText("Upravljaj");
        jMenuItemUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemULActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUL);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Izvodjaci");

        jMenuItemKI.setText("Kreiraj");
        jMenuItemKI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKIActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemKI);

        jMenuItemUI.setText("Upravljaj");
        jMenuItemUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUIActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemUI);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Korisnici");

        jMenuItem3.setText("Kreiraj");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Upravljaj");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 231, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new DogadjajKreirajDialog(this).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemKGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKGActionPerformed
        new GostaKreirajDialog(this).setVisible(true);

    }//GEN-LAST:event_jMenuItemKGActionPerformed

    private void jMenuItemUGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUGActionPerformed
        new GostimaUpravljajForm().setVisible(true);

    }//GEN-LAST:event_jMenuItemUGActionPerformed

    private void jMenuItemULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemULActionPerformed
        LokacijomUpravljajForm ulf = new LokacijomUpravljajForm();
        ulf.setVisible(true);
    }//GEN-LAST:event_jMenuItemULActionPerformed

    private void jMenuItemKLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKLActionPerformed
        LokacijuKreirajDialog lkd = new LokacijuKreirajDialog(this);
        lkd.setVisible(true);
    }//GEN-LAST:event_jMenuItemKLActionPerformed

    private void jMenuItemKIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKIActionPerformed
        IzvodjacaKreirajDialog lkd = new IzvodjacaKreirajDialog(this);
        lkd.setVisible(true);
    }//GEN-LAST:event_jMenuItemKIActionPerformed

    private void jMenuItemUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUIActionPerformed
        IzvodjacimaUpravljajForm iuf = new IzvodjacimaUpravljajForm();
        iuf.setVisible(true);
    }//GEN-LAST:event_jMenuItemUIActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new DogadjajimaUpravljajForm().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da se odjavite?", "ODJAVA", JOptionPane.YES_NO_CANCEL_OPTION);
        if (odgovor == JOptionPane.NO_OPTION) {
            return;
        } else if (odgovor == JOptionPane.YES_OPTION) {
            try {
                Korisnik kor = Session.getInstance().getUlogovaniKorisnik();
                CController.getInstance().logout(kor);
                Session.getInstance().setUlogovaniKorisnik(null);
                LoginForm lf = new LoginForm();
                lf.setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        KorisnikaKreirajDialog lkd = new KorisnikaKreirajDialog(this);
        lkd.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        KorisnicimaUpravljajForm iuf = new KorisnicimaUpravljajForm();
        iuf.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemKG;
    private javax.swing.JMenuItem jMenuItemKI;
    private javax.swing.JMenuItem jMenuItemKL;
    private javax.swing.JMenuItem jMenuItemUG;
    private javax.swing.JMenuItem jMenuItemUI;
    private javax.swing.JMenuItem jMenuItemUL;
    // End of variables declaration//GEN-END:variables
}
