/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import domain.Gost;
import domain.Potvrda;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import tableModels.TableModelGost;

/**
 *
 * @author user
 */
public class PotvrdaGostaKreirajDialog extends javax.swing.JDialog {
private boolean uspeh = false;
    private ArrayList<Potvrda> dodatePotvrde;
    /**
     * Creates new form PotvrdaGostaKreirajDialog
     */
    public PotvrdaGostaKreirajDialog(DogadjajKreirajDialog parent) {
        super(parent, true);
        initComponents();
        setTitle("Dodaj goste na događaj");
        setLocationRelativeTo(parent);
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSviGosti = new javax.swing.JTable();
        jButtonOtkazi = new javax.swing.JButton();
        jButtonDodajIzabrane = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableSviGosti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSviGosti);

        jButtonOtkazi.setText("Otkazi");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });

        jButtonDodajIzabrane.setText("Dodaj Izabrane");
        jButtonDodajIzabrane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajIzabraneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButtonOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jButtonDodajIzabrane, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDodajIzabrane, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajIzabraneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajIzabraneActionPerformed
        int[] selektovaniRedovi = jTableSviGosti.getSelectedRows();
        
        if (selektovaniRedovi.length == 0) {
            JOptionPane.showMessageDialog(this, "Niste izabrali nijednog gosta!", "Greška", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        TableModelGost model = (TableModelGost) jTableSviGosti.getModel();
        HashSet<Gost> jedinstveniGosti = new HashSet<>();
        for (int red : selektovaniRedovi) {
            Gost g = model.getGost(red); 
            jedinstveniGosti.add(g);
        }
        this.dodatePotvrde = new ArrayList<>();
        for (Gost jedinstveniGost : jedinstveniGosti) {
        Potvrda p = new Potvrda(null, jedinstveniGost, false, null); 
        this.dodatePotvrde.add(p);
    }
        this.uspeh = true;
        this.dispose();
    }//GEN-LAST:event_jButtonDodajIzabraneActionPerformed

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajIzabrane;
    private javax.swing.JButton jButtonOtkazi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSviGosti;
    // End of variables declaration//GEN-END:variables
private void pripremiFormu() {
        dodatePotvrde = new ArrayList<>();
        TableModelGost model = new TableModelGost();
        jTableSviGosti.setModel(model);
        // Omogući selektovanje više redova
        jTableSviGosti.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }
public boolean isUspeh() {
        return uspeh;
    }

    public ArrayList<Potvrda> getDodatePotvrde() {
        return dodatePotvrde;
    }

}
